<?xml version="1.0"?>
<robot name="robotic_hand" xmlns:xacro="http://wiki.ros.org/xacro">

  <!-- Define some properties -->
  <xacro:property name="hand_width" value="0.08" />
  <xacro:property name="hand_length" value="0.12" />
  <xacro:property name="hand_height" value="0.02" />
  
  <xacro:property name="finger_width" value="0.015" />
  <xacro:property name="finger_length" value="0.03" />
  <xacro:property name="finger_height" value="0.01" />
  
  <xacro:property name="thumb_width" value="0.018" />
  <xacro:property name="thumb_length" value="0.025" />

  <!-- Materials -->
  <material name="hand_material">
    <color rgba="0.95 0.87 0.73 1.0"/>  <!-- Skin tone -->
  </material>
  
  <material name="finger_material">
    <color rgba="0.92 0.83 0.68 1.0"/>  <!-- Slightly darker skin tone -->
  </material>

  <material name="palm_material">
    <color rgba="0.98 0.90 0.76 1.0"/>  <!-- Palm color -->
  </material>

  <material name="nail_material">
    <color rgba="0.95 0.92 0.88 1.0"/>  <!-- Nail color -->
  </material>

  <!-- Base world link for proper orientation -->
  <link name="world">
    <visual>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <material name="hand_material"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <inertial>
      <mass value="0.001"/>
      <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>

  <!-- Base hand link -->
  <link name="hand_base">
    <visual>
      <geometry>
        <box size="${hand_length} ${hand_width} ${hand_height}"/>
      </geometry>
      <material name="palm_material"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </visual>
    <collision>
      <geometry>
        <box size="${hand_length} ${hand_width} ${hand_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </inertial>
  </link>

  <!-- Joint to orient hand properly (rotate so palm faces camera) -->
  <joint name="hand_orientation_joint" type="fixed">
    <parent link="world"/>
    <child link="hand_base"/>
    <origin xyz="0 0 0.1" rpy="0 -1.5708 0"/>
  </joint>

  <!-- Finger macro -->
  <xacro:macro name="finger" params="prefix x_pos y_pos z_pos rotation">
    
    <!-- Proximal phalanx (base of finger) -->
    <link name="${prefix}_proximal">
      <visual>
        <geometry>
          <box size="${finger_length} ${finger_width} ${finger_height}"/>
        </geometry>
        <material name="finger_material"/>
        <origin xyz="${finger_length/2} 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_length} ${finger_width} ${finger_height}"/>
        </geometry>
        <origin xyz="${finger_length/2} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        <origin xyz="${finger_length/2} 0 0" rpy="0 0 0"/>
      </inertial>
    </link>

    <!-- Middle phalanx -->
    <link name="${prefix}_middle">
      <visual>
        <geometry>
          <box size="${finger_length*0.8} ${finger_width*0.9} ${finger_height*0.9}"/>
        </geometry>
        <material name="finger_material"/>
        <origin xyz="${finger_length*0.4} 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_length*0.8} ${finger_width*0.9} ${finger_height*0.9}"/>
        </geometry>
        <origin xyz="${finger_length*0.4} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.03"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        <origin xyz="${finger_length*0.4} 0 0" rpy="0 0 0"/>
      </inertial>
    </link>

    <!-- Distal phalanx (tip of finger) -->
    <link name="${prefix}_distal">
      <visual>
        <geometry>
          <box size="${finger_length*0.6} ${finger_width*0.8} ${finger_height*0.8}"/>
        </geometry>
        <material name="nail_material"/>
        <origin xyz="${finger_length*0.3} 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_length*0.6} ${finger_width*0.8} ${finger_height*0.8}"/>
        </geometry>
        <origin xyz="${finger_length*0.3} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.02"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        <origin xyz="${finger_length*0.3} 0 0" rpy="0 0 0"/>
      </inertial>
    </link>

    <!-- Joints -->
    <!-- Base joint connecting finger to hand -->
    <joint name="${prefix}_base_joint" type="revolute">
      <parent link="hand_base"/>
      <child link="${prefix}_proximal"/>
      <origin xyz="${x_pos} ${y_pos} ${z_pos}" rpy="0 0 ${rotation}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
    </joint>

    <!-- Proximal-middle joint -->
    <joint name="${prefix}_proximal_joint" type="revolute">
      <parent link="${prefix}_proximal"/>
      <child link="${prefix}_middle"/>
      <origin xyz="${finger_length} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
    </joint>

    <!-- Middle-distal joint -->
    <joint name="${prefix}_middle_joint" type="revolute">
      <parent link="${prefix}_middle"/>
      <child link="${prefix}_distal"/>
      <origin xyz="${finger_length*0.8} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
    </joint>

  </xacro:macro>

  <!-- Thumb macro (slightly different) -->
  <xacro:macro name="thumb" params="prefix x_pos y_pos z_pos rotation">
    
    <!-- Proximal phalanx -->
    <link name="${prefix}_proximal">
      <visual>
        <geometry>
          <box size="${thumb_length} ${thumb_width} ${finger_height}"/>
        </geometry>
        <material name="finger_material"/>
        <origin xyz="${thumb_length/2} 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${thumb_length} ${thumb_width} ${finger_height}"/>
        </geometry>
        <origin xyz="${thumb_length/2} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.04"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        <origin xyz="${thumb_length/2} 0 0" rpy="0 0 0"/>
      </inertial>
    </link>

    <!-- Distal phalanx -->
    <link name="${prefix}_distal">
      <visual>
        <geometry>
          <box size="${thumb_length*0.7} ${thumb_width*0.9} ${finger_height*0.9}"/>
        </geometry>
        <material name="nail_material"/>
        <origin xyz="${thumb_length*0.35} 0 0" rpy="0 0 0"/>
      </visual>
      <collision>
        <geometry>
          <box size="${thumb_length*0.7} ${thumb_width*0.9} ${finger_height*0.9}"/>
        </geometry>
        <origin xyz="${thumb_length*0.35} 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.025"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
        <origin xyz="${thumb_length*0.35} 0 0" rpy="0 0 0"/>
      </inertial>
    </link>

    <!-- Joints -->
    <!-- Base joint -->
    <joint name="${prefix}_base_joint" type="revolute">
      <parent link="hand_base"/>
      <child link="${prefix}_proximal"/>
      <origin xyz="${x_pos} ${y_pos} ${z_pos}" rpy="0 0 ${rotation}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
    </joint>

    <!-- Proximal-distal joint -->
    <joint name="${prefix}_proximal_joint" type="revolute">
      <parent link="${prefix}_proximal"/>
      <child link="${prefix}_distal"/>
      <origin xyz="${thumb_length} 0 0" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1.0"/>
    </joint>

  </xacro:macro>

  <!-- Instantiate the fingers -->
  <!-- Thumb (positioned on side of palm) -->
  <xacro:thumb prefix="thumb" x_pos="0.00" y_pos="-0.030" z_pos="0.0" rotation="-0.7"/>
  
  <!-- Index finger (positioned on front edge of palm, top surface) -->
  <xacro:finger prefix="index" x_pos="0.055" y_pos="-0.030" z_pos="0.0" rotation="0"/>
  
  <!-- Middle finger (positioned on front edge of palm, top surface, center) -->
  <xacro:finger prefix="middle" x_pos="0.058" y_pos="-0.010" z_pos="0.0" rotation="0"/>
  
  <!-- Ring finger (positioned on front edge of palm, top surface) -->
  <xacro:finger prefix="ring" x_pos="0.055" y_pos="0.010" z_pos="0.0" rotation="0"/>
  
  <!-- Pinky finger (positioned on front edge of palm, top surface) -->
  <xacro:finger prefix="pinky" x_pos="0.050" y_pos="0.030" z_pos="0.0" rotation="0"/>

</robot>